"""
Agent 4 — Recruiter Intelligence Agent (Rule-Based, No LLM)
Reads:   precomputed/match_scores/*.json  (top-100 by overall_match_score)
         precomputed/candidate_profiles/*.json
Outputs: precomputed/recruiter_decisions/CAND_XXXXXXX.json

Decision tree (per spec — entirely rule-based):
  1. Blocking risks → DECLINE
  2. Strong technical + product fit + 3+ required skills → STRONGLY_ADVANCE / ADVANCE
  3. Moderate technical + strong product + growth → ADVANCE
  4. 2+ required skills OR unverifiable skills pattern → REVIEW_FURTHER
  5. Default → ADVANCE_IF_POOL_THIN

All fields generated by heuristics and templates — no LLM.
Never imports from src/scoring/ or src/pipeline/.
Checkpoints: skips candidates whose decision file already exists.
"""

import json
import logging
from pathlib import Path

from src.intelligence.paths import (
    DECISIONS_DIR,
    JOB_INTEL_FILE,
    MATCH_DIR,
    PROFILES_DIR,
    is_test_mode,
    top_matches,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s [Agent4-Rec] %(message)s")
logger = logging.getLogger(__name__)

TOP_N = top_matches()   # 20 in test mode, 100 in full mode

# ---------------------------------------------------------------------------
# Interview question templates per recommendation tier
# ---------------------------------------------------------------------------

_INTERVIEW_TEMPLATES = {
    "STRONGLY_ADVANCE": [
        {
            "question": "Walk me through the most complex LLM/RAG system you designed. What retrieval architecture did you choose and why?",
            "priority": "HIGH",
            "dimension": "Technical",
            "what_to_listen_for": "Specific architectural decisions (chunking, reranking, hybrid search), production tradeoffs, latency vs accuracy choices",
        },
        {
            "question": "Tell me about a time you pushed back on a product requirement due to technical constraints. What happened?",
            "priority": "HIGH",
            "dimension": "Cultural",
            "what_to_listen_for": "Directness, confidence in technical judgment, outcome orientation and how they handled stakeholder disagreement",
        },
        {
            "question": "How do you measure success for an AI feature after it ships?",
            "priority": "MEDIUM",
            "dimension": "Product",
            "what_to_listen_for": "Specific metrics (precision, recall, latency, engagement), A/B testing, evaluation frameworks like RAGAS",
        },
        {
            "question": "Describe your approach to fine-tuning vs. RAG for a new use case. How do you decide?",
            "priority": "MEDIUM",
            "dimension": "Technical",
            "what_to_listen_for": "Systematic thinking, tradeoff awareness (cost, latency, data requirements), real examples from their work",
        },
    ],
    "ADVANCE": [
        {
            "question": "Tell me about the most impactful AI/ML feature you shipped. What was the business outcome?",
            "priority": "HIGH",
            "dimension": "Product",
            "what_to_listen_for": "Quantified impact, user empathy, product thinking beyond the model itself",
        },
        {
            "question": "How do you handle evaluation of LLM outputs in production?",
            "priority": "HIGH",
            "dimension": "Technical",
            "what_to_listen_for": "Automated evals, human-in-the-loop, regression testing, specific frameworks",
        },
        {
            "question": "Describe a situation where you had to learn a new technology quickly to unblock the team.",
            "priority": "MEDIUM",
            "dimension": "Growth",
            "what_to_listen_for": "Speed of learning, resourcefulness, self-direction without hand-holding",
        },
    ],
    "REVIEW_FURTHER": [
        {
            "question": "What is your experience with production LLM systems? Walk me through a specific example.",
            "priority": "HIGH",
            "dimension": "Technical",
            "what_to_listen_for": "Depth of real production experience vs. prototype or toy projects — look for specifics",
        },
        {
            "question": "How have you dealt with AI model failures or degradations in production?",
            "priority": "HIGH",
            "dimension": "Technical",
            "what_to_listen_for": "Monitoring setup, incident response, rollback strategy, root cause analysis",
        },
        {
            "question": "What attracts you to an early-stage AI company vs. a larger tech firm?",
            "priority": "MEDIUM",
            "dimension": "Cultural",
            "what_to_listen_for": "Genuine startup motivation, comfort with ambiguity, equity mindset vs. job security",
        },
    ],
    "ADVANCE_IF_POOL_THIN": [
        {
            "question": "What specific AI/ML area are you most excited to grow in over the next 12 months?",
            "priority": "HIGH",
            "dimension": "Growth",
            "what_to_listen_for": "Awareness of own gaps, concrete learning plan, genuine motivation to stretch beyond current skills",
        },
        {
            "question": "Tell me about a project where you had to deliver with limited guidance or resources.",
            "priority": "HIGH",
            "dimension": "Cultural",
            "what_to_listen_for": "Self-directedness, initiative, creative problem-solving under constraints",
        },
        {
            "question": "What is your experience with vector databases and semantic search?",
            "priority": "MEDIUM",
            "dimension": "Technical",
            "what_to_listen_for": "Hands-on vs. theoretical knowledge, specific tools, real use cases vs. tutorials",
        },
    ],
    "DECLINE": [],
}


def _load_json(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _load_top_matches() -> list:
    matches = []
    for path in MATCH_DIR.glob("*.json"):
        try:
            matches.append(_load_json(path))
        except Exception as exc:
            logger.warning(f"Could not load {path}: {exc}")
    matches.sort(key=lambda m: m.get("overall_match_score", 0), reverse=True)
    top = matches[:TOP_N]
    logger.info(f"Loaded {len(top)} match scores (pool: {len(matches)})")
    return top


# ---------------------------------------------------------------------------
# Decision tree
# ---------------------------------------------------------------------------

def _apply_decision_tree(match: dict, profile: dict) -> str:
    score = match.get("overall_match_score", 0)
    skills_matched = match.get("required_skills_matched", [])
    gaps = match.get("identified_gaps", [])
    red_flags = profile.get("red_flags", [])

    disc = match.get("discriminator_scores", {})
    disc_values = list(disc.values())
    technical_score = next(
        (v for k, v in disc.items() if "llm" in k.lower() or "tech" in k.lower()),
        disc_values[0] if disc_values else 0,
    )
    product_score = next(
        (v for k, v in disc.items() if "product" in k.lower()),
        disc_values[1] if len(disc_values) > 1 else 0,
    )

    # 1. Blocking risks
    blocking_keywords = [
        "no product experience", "pure engineer", "no leadership",
        "fraud", "fabricated", "inconsistent dates",
    ]
    has_blocking = any(
        any(kw in flag.lower() for kw in blocking_keywords)
        for flag in red_flags
    ) or any(
        any(kw in gap.lower() for kw in blocking_keywords)
        for gap in gaps
    )
    if has_blocking or score < 0.20:
        return "DECLINE"

    # 2. Strong technical + product + 3+ required skills
    if technical_score >= 0.70 and product_score >= 0.65 and len(skills_matched) >= 3:
        return "STRONGLY_ADVANCE" if score >= 0.80 else "ADVANCE"

    # 3. Moderate technical + strong product + growth
    growth_score = next(
        (v for k, v in disc.items() if "growth" in k.lower() or "ownership" in k.lower()),
        0.5,
    )
    if technical_score >= 0.50 and product_score >= 0.70 and growth_score >= 0.60:
        return "ADVANCE"

    # 4. 2+ required skills OR unverifiable pattern
    unverifiable = [f for f in red_flags if "unverif" in f.lower() or "cannot verify" in f.lower()]
    if len(skills_matched) >= 2 or unverifiable:
        return "REVIEW_FURTHER"

    # 5. Default
    return "ADVANCE_IF_POOL_THIN"


# ---------------------------------------------------------------------------
# Rule-based enrichment (replaces _llm_enrich)
# ---------------------------------------------------------------------------

def _build_trust_assessment(profile: dict) -> dict:
    redrob = profile.get("redrob_trust", {})
    trust_score = 0.45
    signals = []
    verified_claims = []

    if redrob.get("verified_email"):
        trust_score += 0.10
        signals.append({"signal_type": "VERIFIED", "description": "Email verified on Redrob platform", "confidence": 1.0, "field_name": "verified_email"})
        verified_claims.append("Email address verified by Redrob platform")

    if redrob.get("verified_phone"):
        trust_score += 0.05
        signals.append({"signal_type": "VERIFIED", "description": "Phone number verified", "confidence": 1.0, "field_name": "verified_phone"})
        verified_claims.append("Phone number verified")

    github = redrob.get("github_activity_score", -1) or -1
    if github >= 70:
        trust_score += 0.20
        signals.append({"signal_type": "VERIFIED", "description": f"Highly active GitHub contributor (score {int(github)}/100)", "confidence": 0.95, "field_name": "github_activity_score"})
        verified_claims.append(f"Verifiable technical output via GitHub (score {int(github)}/100)")
    elif github >= 50:
        trust_score += 0.10
        signals.append({"signal_type": "PLAUSIBLE", "description": f"Active GitHub contributor (score {int(github)}/100)", "confidence": 0.85, "field_name": "github_activity_score"})

    interview_rate = redrob.get("interview_completion_rate", -1)
    if interview_rate is not None and interview_rate >= 0:
        if interview_rate >= 0.8:
            trust_score += 0.10
            signals.append({"signal_type": "VERIFIED", "description": f"High interview completion rate ({int(interview_rate * 100)}%)", "confidence": 0.90, "field_name": "interview_completion_rate"})
        elif interview_rate < 0.5:
            trust_score -= 0.10
            signals.append({"signal_type": "SUSPICIOUS", "description": f"Low interview completion rate ({int(interview_rate * 100)}%)", "confidence": 0.85, "field_name": "interview_completion_rate"})

    skill_scores = redrob.get("skill_assessment_scores", {}) or {}
    if skill_scores:
        top_skill = max(skill_scores, key=skill_scores.get)
        top_val = skill_scores[top_skill]
        if top_val >= 75:
            trust_score += 0.10
            signals.append({"signal_type": "VERIFIED", "description": f"Platform-assessed {top_skill}: {int(top_val)}/100", "confidence": 0.95, "field_name": "skill_assessment_scores"})
            verified_claims.append(f"Skill assessment score: {top_skill} = {int(top_val)}/100")

    completeness = redrob.get("profile_completeness_score", 0) or 0
    if completeness >= 80:
        trust_score += 0.05
        signals.append({"signal_type": "PLAUSIBLE", "description": f"High profile completeness ({int(completeness)}%)", "confidence": 0.80, "field_name": "profile_completeness_score"})

    # Unverifiable claims are always present
    unverifiable = [
        "Career history claims beyond platform verification require reference checks",
        "Skill proficiency levels self-reported — validate in technical screen",
    ]

    trust_score = round(min(max(trust_score, 0.0), 1.0), 2)
    if trust_score >= 0.75:
        trust_tier = "HIGH"
    elif trust_score >= 0.50:
        trust_tier = "MEDIUM"
    else:
        trust_tier = "LOW"

    return {
        "overall_trust_score": trust_score,
        "trust_tier": trust_tier,
        "signals": signals,
        "verified_claims": verified_claims,
        "unverifiable_claims": unverifiable,
        "red_flags": profile.get("red_flags", []),
    }


def _build_fit_dimensions(match: dict, profile: dict) -> dict:
    disc = match.get("discriminator_scores", {})
    name = profile.get("name", "Candidate")
    title = profile.get("current_title", "")
    company = profile.get("current_company", "")
    skills = profile.get("top_skills", [])
    matched = match.get("required_skills_matched", [])
    gaps = match.get("identified_gaps", [])
    outcome_score = profile.get("outcome_language_score", 0)
    trajectory = profile.get("career_trajectory", "mixed")

    # Technical: average of LLM+MLOps discriminators
    tech_keys = [k for k in disc if "llm" in k.lower() or "rag" in k.lower() or "mlops" in k.lower() or "python" in k.lower()]
    tech_score = sum(disc[k] for k in tech_keys) / len(tech_keys) if tech_keys else (matched and 0.6 or 0.35)

    # Product: product-sense discriminator
    prod_keys = [k for k in disc if "product" in k.lower()]
    prod_score = sum(disc[k] for k in prod_keys) / len(prod_keys) if prod_keys else profile.get("product_company_fraction", 0.4)

    # Cultural: founding/ownership discriminator
    cult_keys = [k for k in disc if "founding" in k.lower() or "ownership" in k.lower()]
    cult_score = sum(disc[k] for k in cult_keys) / len(cult_keys) if cult_keys else profile.get("ownership_language_score", 0.5)

    # Growth: career trajectory + outcome language
    traj_map = {"upward": 0.80, "lateral": 0.60, "mixed": 0.50, "downward": 0.30, "unknown": 0.50}
    growth_score = min(traj_map.get(trajectory, 0.50) + outcome_score * 0.15, 1.0)

    tech_evidence = []
    if matched:
        tech_evidence.append(f"{name} ({title} at {company}) has {', '.join(matched[:2])} matching role requirements")
    elif skills:
        tech_evidence.append(f"{name} brings {', '.join(skills[:2])} to the role")

    prod_evidence = []
    frac = profile.get("product_company_fraction", 0)
    if frac > 0.6:
        prod_evidence.append(f"{int(frac * 100)}% of career at product companies")
    elif frac > 0.3:
        prod_evidence.append(f"{int(frac * 100)}% product company experience")

    growth_evidence = []
    if trajectory == "upward":
        growth_evidence.append(f"Upward career trajectory with {profile.get('career_trajectory', 'progressive')} progression")

    tech_gaps = [g for g in gaps if "llm" in g.lower() or "rag" in g.lower() or "mlops" in g.lower() or "technical" in g.lower()]
    prod_gaps = [g for g in gaps if "product" in g.lower() or "user" in g.lower()]

    return {
        "technical": {
            "score": round(min(max(tech_score, 0), 1), 2),
            "evidence": tech_evidence,
            "gaps": tech_gaps[:1],
        },
        "product": {
            "score": round(min(max(prod_score, 0), 1), 2),
            "evidence": prod_evidence,
            "gaps": prod_gaps[:1],
        },
        "cultural": {
            "score": round(min(max(cult_score, 0), 1), 2),
            "evidence": ["Ownership language in career descriptions suggests initiative"] if cult_score > 0.5 else [],
            "gaps": [],
        },
        "growth": {
            "score": round(min(max(growth_score, 0), 1), 2),
            "evidence": growth_evidence,
            "gaps": [],
        },
    }


def _build_hiring_risks(match: dict, profile: dict, recommendation: str) -> list:
    risks = []
    gaps = match.get("identified_gaps", [])
    red_flags = profile.get("red_flags", [])
    name = profile.get("name", "Candidate")
    high_sev = recommendation in ("REVIEW_FURTHER", "ADVANCE_IF_POOL_THIN", "DECLINE")

    for gap in gaps[:2]:
        risks.append({
            "risk_type": "Skill Gap",
            "severity": "HIGH" if high_sev else "MEDIUM",
            "description": f"{name}: {gap}",
            "mitigation": "Probe depth of adjacent skills and practical project examples in technical screen",
            "is_blocking": recommendation == "DECLINE",
        })

    for flag in red_flags[:1]:
        risks.append({
            "risk_type": "Profile Signal",
            "severity": "MEDIUM",
            "description": f"{name}: {flag}",
            "mitigation": "Raise directly in intro call and assess candidate response",
            "is_blocking": False,
        })

    if not risks:
        risks.append({
            "risk_type": "Standard Verification",
            "severity": "LOW",
            "description": f"Standard background check and reference calls required for {name}",
            "mitigation": "Include in post-offer process",
            "is_blocking": False,
        })

    return risks


def _build_interview_focus(recommendation: str, profile: dict, match: dict) -> list:
    templates = _INTERVIEW_TEMPLATES.get(recommendation, _INTERVIEW_TEMPLATES["REVIEW_FURTHER"])
    name = profile.get("name", "Candidate")
    title = profile.get("current_title", "")
    skills = profile.get("top_skills", [])

    questions = []
    for tmpl in templates:
        q = dict(tmpl)
        # Personalise question slightly by injecting candidate context
        if skills and "{skill}" in q.get("question", ""):
            q["question"] = q["question"].replace("{skill}", skills[0])
        questions.append(q)

    return sorted(questions, key=lambda q: {"HIGH": 0, "MEDIUM": 1, "LOW": 2}.get(q.get("priority", "LOW"), 2))


def _build_rationale(match: dict, profile: dict, recommendation: str) -> str:
    name = profile.get("name", "this candidate")
    title = profile.get("current_title", "unknown role")
    company = profile.get("current_company", "their company")
    skills = match.get("required_skills_matched", profile.get("top_skills", []))
    gaps = match.get("identified_gaps", [])
    score = int(match.get("overall_match_score", 0) * 100)
    skill1 = skills[0] if skills else "technical background"
    skill2 = skills[1] if len(skills) > 1 else ""
    gap = gaps[0] if gaps else None

    templates = {
        "STRONGLY_ADVANCE": (
            f"{name} ({title} at {company}) is a strong match at {score}/100 — "
            f"{skill1}{f' and {skill2}' if skill2 else ''} directly cover our core LLM/RAG requirements. "
            f"{'No blocking gaps identified.' if not gap else f'Minor gap: {gap}.'} Advance to technical screen immediately."
        ),
        "ADVANCE": (
            f"{name} ({title} at {company}) scores {score}/100 with {skill1} aligned to role requirements. "
            f"{f'Gap: {gap}.' if gap else 'No critical gaps.'} Strong enough profile to advance to phone screen."
        ),
        "REVIEW_FURTHER": (
            f"{name} ({title} at {company}) shows adjacent fit at {score}/100 via {skill1}, "
            f"but {gap if gap else 'full role alignment'} needs verification. "
            f"Review if primary pipeline candidates are unavailable."
        ),
        "ADVANCE_IF_POOL_THIN": (
            f"{name} ({title} at {company}) is below primary threshold at {score}/100 — "
            f"{gap if gap else 'multiple gaps present'}. "
            f"Include as backup if top-tier pool is insufficient."
        ),
        "DECLINE": (
            f"{name} ({title} at {company}) scores {score}/100 and does not meet minimum requirements. "
            f"{gap if gap else 'Multiple gaps'} make this a poor fit for the Senior AI Engineer role."
        ),
    }
    return templates.get(recommendation, templates["REVIEW_FURTHER"])


def _build_timing_assessment(profile: dict) -> dict:
    redrob = profile.get("redrob_trust", {})
    open_to_work = redrob.get("open_to_work_flag", False)
    notice_days = redrob.get("notice_period_days", 30) or 30
    total_months = profile.get("total_months", 0)

    if open_to_work:
        urgency = f"Actively open to work with {notice_days}-day notice — high availability signal"
        likely = True
    elif total_months and total_months % 24 < 6:
        urgency = "Recent role change pattern suggests may be open to new opportunities"
        likely = True
    else:
        urgency = "No active availability signal — outreach response rate unknown"
        likely = False

    return {
        "current_tenure_months": total_months,
        "likely_available": likely,
        "urgency_signal": urgency,
        "estimated_notice_weeks": (notice_days // 7) if notice_days else 4,
    }


def _build_top_evidence(match: dict, profile: dict) -> list:
    evidence = match.get("match_evidence", [])
    if evidence:
        return evidence[:2]
    name = profile.get("name", "Candidate")
    title = profile.get("current_title", "")
    company = profile.get("current_company", "")
    skills = profile.get("top_skills", [])
    score = int(match.get("overall_match_score", 0) * 100)
    return [
        f"{name} ({title} at {company}) — overall match {score}/100",
        f"Top skills: {', '.join(skills[:3])}" if skills else "Skills not verified",
    ]


def _rule_enrich(match: dict, profile: dict, recommendation: str) -> dict:
    fit_dims = _build_fit_dimensions(match, profile)
    return {
        "trust_assessment": _build_trust_assessment(profile),
        "fit_dimensions": fit_dims,
        "hiring_risks": _build_hiring_risks(match, profile, recommendation),
        "interview_focus": _build_interview_focus(recommendation, profile, match),
        "recommendation_rationale": _build_rationale(match, profile, recommendation),
        "timing_assessment": _build_timing_assessment(profile),
        "top_evidence": _build_top_evidence(match, profile),
    }


def _build_decision(match: dict, profile: dict, recommendation: str, enrichment: dict) -> dict:
    fd = enrichment.get("fit_dimensions", {})

    def dim(key: str) -> dict:
        return fd.get(key, {"score": 0.5, "evidence": [], "gaps": []})

    return {
        "candidate_id": match["candidate_id"],
        "name": profile.get("name", ""),
        "current_title": profile.get("current_title", ""),
        "current_company": profile.get("current_company", ""),
        "recommendation": recommendation,
        "trust_assessment": enrichment.get("trust_assessment", {}),
        "fit_assessment": {
            "technical": dim("technical"),
            "product": dim("product"),
            "cultural": dim("cultural"),
            "growth": dim("growth"),
            "overall": round(
                dim("technical")["score"] * 0.35
                + dim("product")["score"] * 0.30
                + dim("cultural")["score"] * 0.20
                + dim("growth")["score"] * 0.15,
                3,
            ),
        },
        "hiring_risks": enrichment.get("hiring_risks", []),
        "interview_focus": enrichment.get("interview_focus", []),
        "recommendation_rationale": enrichment.get("recommendation_rationale", ""),
        "timing_assessment": enrichment.get("timing_assessment"),
        "required_skills_matched": match.get("required_skills_matched", []),
        "overall_match_score": match.get("overall_match_score", 0),
        "top_evidence": enrichment.get("top_evidence", []),
    }


def run() -> list:
    logger.info("=" * 60)
    mode_label = "TEST" if is_test_mode() else "FULL"
    logger.info(f"Agent 4: Recruiter Intelligence  [{mode_label} — top-{TOP_N}]  [Rule-Based — No LLM]")
    logger.info("=" * 60)

    DECISIONS_DIR.mkdir(parents=True, exist_ok=True)

    if not JOB_INTEL_FILE.exists():
        raise FileNotFoundError(f"Missing {JOB_INTEL_FILE}. Run Agent 1 first.")

    all_matches = _load_top_matches()

    pending = [
        m for m in all_matches
        if not (DECISIONS_DIR / f"{m['candidate_id']}.json").exists()
    ]
    logger.info(f"Pending: {len(pending)} | Already decided: {len(all_matches) - len(pending)}")

    processed = 0
    failed = 0

    for i, match in enumerate(pending):
        cid = match["candidate_id"]
        if (i + 1) % 10 == 0 or i == 0:
            logger.info(f"  [{i + 1}/{len(pending)}] {cid}")

        profile_path = PROFILES_DIR / f"{cid}.json"
        if not profile_path.exists():
            logger.warning(f"  No profile for {cid} — skipping")
            failed += 1
            continue

        try:
            profile = _load_json(profile_path)
            recommendation = _apply_decision_tree(match, profile)
            enrichment = _rule_enrich(match, profile, recommendation)
            decision = _build_decision(match, profile, recommendation, enrichment)

            out_path = DECISIONS_DIR / f"{cid}.json"
            with open(out_path, "w", encoding="utf-8") as f:
                json.dump(decision, f, indent=2)
            processed += 1

        except Exception as exc:
            logger.warning(f"  x {cid}: {exc}")
            failed += 1

    logger.info(f"✓ Agent 4 complete — processed: {processed}, failed: {failed}")

    all_decisions = []
    for m in all_matches:
        path = DECISIONS_DIR / f"{m['candidate_id']}.json"
        if path.exists():
            with open(path, encoding="utf-8") as f:
                all_decisions.append(json.load(f))
    return all_decisions


if __name__ == "__main__":
    run()
