-- ============================================================
-- HireIQ / Sententia V3.10 Knowledge Store Schema
--
-- Purpose:
-- Offline indexed knowledge base for recruiter intelligence.
--
-- This database NEVER replaces the existing JSON artifacts.
-- It mirrors them in SQLite for fast retrieval by the AI layer.
--
-- Source of truth:
-- precomputed/*.json
--
-- Generated by:
-- precompute_v3.py
-- ============================================================

PRAGMA foreign_keys = ON;

---------------------------------------------------------------
-- Job Intelligence
---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS job (
    job_id TEXT PRIMARY KEY,
    role_name TEXT,
    created_at TEXT,
    payload TEXT NOT NULL
);

---------------------------------------------------------------
-- Candidate Intelligence (Agent 2)
---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS candidate_profiles (
    candidate_id TEXT PRIMARY KEY,

    name TEXT,
    current_title TEXT,
    current_company TEXT,

    narrative_type TEXT,
    consistency_score REAL,
    fast_score REAL,
    years_of_experience REAL,

    payload TEXT NOT NULL
);

---------------------------------------------------------------
-- Matching Intelligence (Agent 3)
---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS match_scores (
    candidate_id TEXT PRIMARY KEY,

    overall_match_score REAL,

    payload TEXT NOT NULL,

    FOREIGN KEY(candidate_id)
        REFERENCES candidate_profiles(candidate_id)
);

---------------------------------------------------------------
-- Recruiter Intelligence (Agent 4)
---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS recruiter_decisions (
    candidate_id TEXT PRIMARY KEY,

    recommendation TEXT,
    overall_match_score REAL,

    payload TEXT NOT NULL,

    FOREIGN KEY(candidate_id)
        REFERENCES candidate_profiles(candidate_id)
);

---------------------------------------------------------------
-- Metadata
---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS metadata (
    key TEXT PRIMARY KEY,
    value TEXT
);

---------------------------------------------------------------
-- Useful indexes
---------------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_candidate_fast_score
ON candidate_profiles(fast_score DESC);

CREATE INDEX IF NOT EXISTS idx_candidate_experience
ON candidate_profiles(years_of_experience);

CREATE INDEX IF NOT EXISTS idx_match_score
ON match_scores(overall_match_score DESC);

CREATE INDEX IF NOT EXISTS idx_recommendation
ON recruiter_decisions(recommendation);

CREATE INDEX IF NOT EXISTS idx_decision_score
ON recruiter_decisions(overall_match_score DESC);

---------------------------------------------------------------
-- Pipeline Decisions (recruiter actions)
---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS pipeline_decisions (
    candidate_id TEXT PRIMARY KEY,
    status TEXT NOT NULL CHECK(status IN ('advanced', 'setaside')),
    decided_at TEXT
);

---------------------------------------------------------------
-- Users (auth)
---------------------------------------------------------------

CREATE TABLE IF NOT EXISTS users (
    user_id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT,
    name TEXT,
    created_at TEXT DEFAULT (datetime('now'))
);